# Generated by Django 6.0 on 2025-12-10 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "STAFF"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "STAFF"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
